import type { FastifyInstance } from 'fastify'
import { createClient } from '@supabase/supabase-js'
import { applyRecoveryAdjustment } from '@helux/ai'
import type { AdjustedWorkoutPlanView } from '@helux/types'
import { getActiveMesocycle, findPendingSessionIndex } from '../services/mesocycle.service'
import { generateAndSaveMesocycle } from '../services/plan-generation.service'
import { computeRecoveryFromSamples, type HealthSample } from '../services/recovery.service'

export async function workoutLatestPlanRoutes(app: FastifyInstance): Promise<void> {
  const supabaseUrl = process.env.SUPABASE_URL!
  const supabaseAnonKey = process.env.SUPABASE_ANON_KEY!

  app.get('/workout/latest-plan', async (request, reply) => {
    const authHeader = request.headers.authorization
    if (!authHeader?.startsWith('Bearer ')) {
      return reply.code(401).send({ error: 'Unauthorized' })
    }
    const token = authHeader.slice(7)

    const verifyClient = createClient(supabaseUrl, supabaseAnonKey)
    const { data: { user }, error: authError } = await verifyClient.auth.getUser(token)
    if (authError || !user) {
      return reply.code(401).send({ error: 'Unauthorized' })
    }

    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: `Bearer ${token}` } },
    })

    let mesocycle
    try {
      mesocycle = await getActiveMesocycle(user.id, supabase)
    } catch (error) {
      app.log.error(error, 'workout-latest-plan: failed to load active mesocycle')
      return reply.code(500).send({ error: 'Internal Server Error' })
    }

    if (!mesocycle) {
      // First-ever use: bootstrap the first mesocycle instead of waiting on
      // POST /workout/generate (the old manual single-session flow).
      void generateAndSaveMesocycle(user.id, token, supabase, app.log)
      const view: AdjustedWorkoutPlanView = {
        mesocycleId: null,
        generatedAt: null,
        today: null,
        upcoming: [],
        progress: null,
        status: 'generating',
      }
      return reply.send(view)
    }

    const pendingIndex = findPendingSessionIndex(mesocycle.sessions)
    const completed = mesocycle.sessions.filter((s) => s.completedAt !== null).length
    const total = mesocycle.sessions.length

    if (pendingIndex === -1) {
      // The active mesocycle is fully completed; the next one is already
      // being generated by the write-path (see plan-generation.service.ts).
      const view: AdjustedWorkoutPlanView = {
        mesocycleId: mesocycle.id,
        generatedAt: mesocycle.generated_at,
        today: null,
        upcoming: [],
        progress: { completed, total },
        status: 'generating',
      }
      return reply.send(view)
    }

    const since = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString()
    const { data: samples, error: samplesError } = await supabase
      .from('health_samples')
      .select('type, value, unit, start_at')
      .eq('user_id', user.id)
      .gte('start_at', since)
      .order('start_at', { ascending: false })

    if (samplesError) {
      app.log.error(samplesError, 'workout-latest-plan: failed to load recovery samples')
      return reply.code(500).send({ error: 'Internal Server Error' })
    }

    const recoveryData = samples && samples.length > 0 ? [computeRecoveryFromSamples(samples as HealthSample[])] : []
    const pendingSession = mesocycle.sessions[pendingIndex]
    const today = applyRecoveryAdjustment(pendingSession, recoveryData)
    const upcoming = mesocycle.sessions.slice(pendingIndex + 1).map((s) => ({ letter: s.letter, focus: s.focus }))

    const view: AdjustedWorkoutPlanView = {
      mesocycleId: mesocycle.id,
      generatedAt: mesocycle.generated_at,
      today,
      upcoming,
      progress: { completed, total },
    }
    return reply.send(view)
  })
}
